language: cpp
os: linux
dist: xenial
compiler: gcc
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install qt512base qt512multimedia qt512imageformats qt512translations libgl1-mesa-dev libgl1-mesa-glx libqtermwidget5-0-dev libqtermwidget5-0 -y
  - source /opt/qt512/bin/qt512-env.sh

script:
  - cd Commander/
  - /opt/qt512/bin/qmake ./Commander.pro -spec linux-g++ && /usr/bin/make qmake_all
  - make

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

notifications:
  email:
    recipients:
      - jonasjaguar@jagudev.net
    on_success: always
    on_failure: always
